project invisiobserver {
  database_type: 'mariadb'
  Note: '''
    # Database to manage Wireshark Data
    ** markdown **
  '''
}

Table capture {
  id integer [pk, not null]
  _index TEXT
  _type TINYTEXT
  _score TEXT
}

Table frame {
  id integer [pk, ref: - capture.id]
  interface_id integer
  interface_name TEXT
  interface_description TEXT
  encap_type integer
  time datetime
  time_epoch double
  time_delta double
  time_delta_displayed double
  time_relative double
  number integer // id in capture
  len integer
  cap_len integer
  marked integer
  ignored integer
  protocols TEXT
  coloring_rule_name TINYTEXT
  coloring_rule_string TINYTEXT
}


Table eth {
  id integer [pk, ref: - capture.id]
  dst VARCHAR(17) [ref: > eth_destination.dst_ip,
  note: 'ff:ff:ff:ff:ff:ff']
  src VARCHAR(17) [ref: > eth_source.src_ip,
  note: 'ff:ff:ff:ff:ff:ff']
  type INTEGER
}

Tablegroup eth_route {
  eth_destination
  eth_source
}

Table eth_destination {
  dst_ip VARCHAR(17) [pk, 
  note: 'ff:ff:ff:ff:ff:ff']
  dst_dst_resolved TINYTEXT
  dst_dst_oui integer
  dst_addr VARCHAR(17) [ 
  note: 'ff:ff:ff:ff:ff:ff']
  dst_addr_resolved TINYTEXT
  dst_dst_lg integer
  dst_lg integer
  dst_dst_ig integer
  dst_ig integer
}

Table eth_source {
  src_ip VARCHAR(17) [pk, 
  note: 'ff:ff:ff:ff:ff:ff']
  src_src_resolved TINYTEXT
  src_src_oui integer
  src_src_oui_resolved TINYTEXT
  src_addr VARCHAR(17) [ 
  note: 'ff:ff:ff:ff:ff:ff']
  src_addr_resolved TEXT
  src_addr_oui integer
  src_addr_oui_resolved TEXT
  src_src_lg integer
  src_lg integer
  src_src_ig integer
  src_ig integer
}

Table ip {
  id integer [pk, ref: - capture.id]
  addr VARCHAR(15) [default: NULL]
  bogus_header_length TEXT [default: NULL]
  bogus_ip_length TEXT [default: NULL]
  bogus_ip_version TEXT [default: NULL]
  checksum "smallint unsigned" [default: 0]
  checksum_status "tinyint unsigned" [default: 0]
  checksum_bad tinyint(1) [default: 0]
  checksum_bad_expert TEXT [default: NULL]
  checksum_calculated "smallint unsigned" [default: 0]
  checksum_good tinyint(1) [default: 0]
  cipso_categories TEXT [default: NULL]
  cipso_doi "integer unsigned" [default: 0]
  cipso_malformed TEXT [default: NULL]
  cipso_sensitivity_level "tinyint unsigned" [default: 0]
  cipso_tag_data blob [default: NULL]
  cipso_tag_type "tinyint unsigned" [default: 0]
  cur_rt VARCHAR(15) [default: NULL]
  cur_rt_host TEXT [default: NULL]
  dsfield "tinyint unsigned" [default: NULL]
  dsfield_ce "tinyint unsigned" [default: NULL]
  dsfield_dscp "tinyint unsigned" [default: NULL]
  dsfield_ecn "tinyint unsigned" [default: NULL]
  dsfield_ect "tinyint unsigned" [default: NULL]
  dst VARCHAR(15) [default: NULL]
  dst_host VARCHAR(15) [default: NULL]
  empty_rt VARCHAR(15) [default: NULL]
  empty_rt_host TEXT [default: NULL]
  evil_packet TEXT [default: NULL]
  flags "tinyint unsigned" [default: 0]
  flags_df tinyint(1) [default: 0]
  flags_mf tinyint(1) [default: 0]
  flags_rb tinyint(1) [default: 0]
  flags_sf tinyint(1) [default: 0]
  flags_offset "smallint unsigned" [default: 0]
  fragment VARCHAR(15) [default: NULL]
  geoip_asnum "integer unsigned" [default: 0]
  geoip_city TEXT [default: NULL]
  geoip_country TEXT [default: NULL]
  geoip_country_iso TEXT [default: NULL]
  geoip_dst_asnum "integer unsigned" [default: 0]
  geoip_dst_city TEXT [default: NULL]
  geoip_dst_country TEXT [default: NULL]
  geoip_dst_country_iso TEXT [default: NULL]
  geoip_dst_isp TEXT [default: NULL]
  geoip_dst_lat double [default: 0]
  geoip_dst_lon double [default: 0]
  geoip_dst_org TEXT [default: NULL]
  geoip_dst_summary TEXT [default: NULL]
  geoip_isp TEXT [default: NULL]
  geoip_lat double [default: 0]
  geoip_lon double [default: 0]
  geoip_org TEXT [default: NULL]
  geoip_src_asnum "integer unsigned" [default: 0]
  geoip_src_city TEXT [default: NULL]
  geoip_src_country TEXT [default: NULL]
  geoip_src_country_iso TEXT [default: NULL]
  geoip_src_isp TEXT [default: NULL]
  geoip_src_lat double [default: 0]
  geoip_src_lon double [default: 0]
  geoip_src_org TEXT [default: NULL]
  geoip_org_summary TEXT [default: NULL]
  hdr_len "tinyint unsigned" [default: 0]
  host TEXT [default: NULL]
  ip_id "smallint unsigned" [default: 0]
  len "smallint unsigned" [default: 0]
  nop TEXT [default: NULL]
  opt_addr VARCHAR(15) [default: NULL]
  opt_ext_sec_add_sec_info blob [default: NULL]
  opt_ext_sec_add_sec_info_format_code "tinyint unsigned" [default: 0]
  opt_flag "tinyint unsigned" [default: 0]
  opt_id_num "smallint unsigned" [default: 0]
  opt_len "tinyint unsigned" [default: 0]
  opt_len_invalid TEXT [default: NULL]
  opt_mtu "smallint unsigned" [default: 0]
  opt_ohc "smallint unsigned" [default: 0]
  opt_originator VARCHAR(15) [default: NULL]
  opt_overflow "tinyint unsigned" [default: 0]
  opt_padding blob [default: NULL]
  opt_ptr "tinyint unsigned" [default: 0]
  opt_ptr_before_addr TEXT [default: NULL]
  opt_ptr_middle_addr TEXT [default: NULL]
  opt_qs_func "tinyint unsigned" [default: 0]
  opt_qs_nonce "integer unsigned" [default: 0]
  opt_qs_rate "tinyint unsigned" [default: 0]
  opt_qs_reserved "integer unsigned" [default: 0]
  opt_qs_ttl "tinyint unsigned" [default: 0]
  opt_qs_ttl_diff "tinyint unsigned" [default: 0]
  opt_qs_unused "tinyint unsigned" [default: 0]
  opt_ra "smallint unsigned" [default: 0]
  opt_rhc "smallint unsigned" [default: 0]
  opt_sec_cl "tinyint unsigned" [default: 0]
  opt_sec_prot_auth_doe tinyint(1) [default: 0]
  opt_sec_prot_auth_flags "tinyint unsigned" [default: 0]
  opt_sec_prot_auth_fti tinyint(1) [default: 0]
  opt_sec_prot_auth_genser tinyint(1) [default: 0]
  opt_sec_prot_auth_nsa tinyint(1) [default: 0]
  opt_sec_prot_auth_sci tinyint(1) [default: 0]
  opt_sec_prot_auth_siop_esi tinyint(1) [default: 0]
  opt_sec_prot_auth_unassigned "tinyint unsigned" [default: 0]
  opt_sec_rfc791_comp "smallint unsigned" [default: 0]
  opt_sec_rfc791_hr TEXT [default: NULL]
  opt_sec_rfc791_sec "tinyint unsigned" [default: 0]
  opt_sec_rfc791_ttc TEXT [default: NULL]
  opt_sid "smallint unsigned" [default: 0]
  opt_time_stamp "integer unsigned" [default: 0]
  opt_time_stamp_addr VARCHAR(15) [default: NULL]
  opt_type "tinyint unsigned" [default: 0]
  opt_type_class "tinyint unsigned" [default: 0]
  opt_type_copy tinyint(0) [default: 0]
  opt_type_number "tinyint unsigned" [default: 0]
  proto "tinyint unsigned" [default: 0]
  reassembled_data blob [default: NULL]
  reassembled_length "integer unsigned" [default: 0]
  reassembled_in "integer unsigned" [default: 0, note: 'frame reference number']
  rec_rt VARCHAR(15) [default: NULL]
  rec_rt_host TEXT [default: NULL]
  src VARCHAR(15) [default: NULL]
  src_host TEXT [default: NULL]
  src_rt VARCHAR(15) [default: NULL]
  src_rt_host TEXT [default: NULL]
  subopt_too_long TEXT [default: NULL]
  tos "tinyint unsigned" [default: 0]
  tos_cost tinyint(1) [default: 0]
  tos_delay tinyint(1) [default: 0]
  tos_precedence "tinyint unsigned" [default: 0]
  tos_reliability tinyint(1) [default: 0]
  tos_throughput tinyint(1) [default: 0]
  ttl "tinyint unsigned" [default: 0]
  ttl_lncb TEXT [default: NULL]
  ttl_too_small TEXT [default: NULL]
  version "tinyint unsigned" [default: 0]
  
 
  
}


Table arp {
  id integer [pk, ref: - capture.id]
  dst_atm_num_e164 TEXT [default: NULL]
  dst_atm_num_nsap blob [default: NULL]
  dst_atm_subaddr blob [default: NULL]
  dst_drarp_error_status "smallint unsigned" [default: 0]
  dst_hlen "tinyint unsigned" [default: 0]
  dst_htype tinyint(1) [default: 0]
  dst_hw blob [default: NULL]
  dst_hw_ax25 blob [default: NULL]
  dst_hw_mac TEXT [default: NULL]
  dst_pln "tinyint unsigned" [default: 0]
  dst_proto blob [default: NULL]
  dst_proto_ipv4 VARCHAR(15) [default: NULL]
  dst_slen "tinyint unsigned" [default: 0]
  dst_stype tinyint(1) [default: 0]
  dup_addr_detected TEXT [default: NULL]
  dup_addr_frame integer [note: 'references earlier frame number', default: -1]  
  hw_size "tinyint unsigned" [default: 0]
  hw_type "smallint unsigned" [default: 0]
  is_announcement tinyint(1) [default: 0]
  isgratuitous tinyint(1) [default: 0]
  isprobe tinyint(1) [default: 0]
  opcode "smallint unsigned" [default: 0]
  packet_storm_detected TEXT [default: NULL]
  proto_size "tinyint unsigned" [default: 0]
  proto_type "smallint unsigned" [default: 0]
  seconds_since_dup_addr_frame "integer unsigned" [note: 'references earlier frame number', default: -1]  
  src_atm_afi "tinyint unsigned" [default: 0]
  src_atm_afi_unknown TEXT [default: NULL]
  src_atm_data_country_code "smallint unsigned" [default: 0]
  src_atm_data_country_code_group "smallint unsigned" [default: 0]
  src_atm_e164_isdn blob [default: NULL]
  src_atm_e164_isdn_group blob [default: NULL]
  src_atm_end_sys_identifier blob [default: NULL]
  src_atm_high_order_dsp blob [default: NULL]
  src_atm_intl_code_designator "smallint unsigned" [default: 0]
  src_atm_intl_code_designator_group "smallint unsigned" [default: 0]
  src_atm_num_e164 TEXT [default: NULL]
  src_atm_num_nsap blob [default: NULL]
  src_atm_rest_of_addr blob [default: NULL]
  src_atm_selector "tinyint unsigned" [default: 0]
  src_atm_subaddr blob [default: NULL]
  src_hlen "smallint unsigned" [default: 0]
  src_htype tinyint(1) [default: 0]
  src_hw blob [default: NULL]
  src_hw_ax25 blob [default: NULL]
  src_hw_mac TEXT [default: NULL]
  src_pln "tinyint unsigned" [default: 0]
  src_proto blob [default: NULL]
  src_proto_ipv4 VARCHAR(15) [default: NULL]
  src_slen "tinyint unsigned" [default: 0]
  src_stype tinyint(1) [default: 0]
}

Table rarp {id integer [pk]
} // Placeholder

Table ppp {id integer [pk]
} // Placeholder

Table ipv6 {
  id integer [pk]
  ipv6_6to4_gw_ipv4 VARCHAR(15) [default: NULL]
  ipv6_6to4_sla_id "smallint unsigned" [default: 0]
  addr VARCHAR(17) [default: NULL]
  bogus_length TEXT [default: NULL]
  bogus_version TEXT [default: NULL]
  bogus_payload_length TEXT [default: NULL]
  class "integer unsigned" [default: 0]
  dst VARCHAR(17) [default: NULL]
  dst_6to4_gw_ipv4 VARCHAR(15) [default: NULL]
  dst_6to4_sla_id "smallint unsigned" [default: 0]
  dst_addr_not_multicast TEXT [default: NULL]
  dst_embed_ipv4 VARCHAR(15) [default: NULL]
  dst_host TEXT [default: NULL]
  dst_isatap_ipv4 VARCHAR(15) [default: NULL]
  dst_opt TEXT [default: NULL]
  dst_sa_mac TEXT [default: NULL]
  dst_slaac_mac TEXT [default: NULL]
  dst_tc_ipv4 VARCHAR(15) [default: NULL]
  dst_tc_port "smallint unsigned" [default: 0]
  dst_ts_ipv4 VARCHAR(15) [default: NULL]
  dstopts TEXT [default: NULL]
  dstopts_length "tinyint unsigned" [default: 0]
  dstopts_nxt "tinyint unsigned" [default: 0]
  embed_ipv4 VARCHAR(15) [default: NULL]
  flow "integer unsigned" [default: 0]
  fraghdr TEXT [default: NULL]
  fraghdr_ident "integer unsigned" [default: 0]
  fraghdr_more tinyint(1) [default: 0]
  fraghdr_nxt "tinyint unsigned" [default: 0]
  fraghdr_offset "smallint unsigned" [default: 0]
  fraghdr_reserved_bits "smallint unsigned" [default: 0]
  fraghdr_reserved_octet "tinyint unsigned" [default: 0]
  fragment TEXT [default: NULL]
  fragment_count "integer unsigned" [default: 0]
  fragment_error TEXT [default: NULL]
  fragment_id "integer unsigned" [default: 0]
  fragment_more tinyint(1) [default: 0]
  fragment_multipletails tinyint(1) [default: 0]
  fragment_nxt "smallint unsigned" [default: 0]
  fragment_offset "smallint unsigned" [default: 0]
  fragment_overlap tinyint(1) [default: 0]
  fragment_overlap_conflict tinyint(1) [default: 0]
  fragment_reserved_bits "smallint unsigned" [default: 0]
  fragment_reserved_octet "smallint unsigned" [default: 0]
  fragment_toolongfragment tinyint(1) [default: 0]
  fragments TEXT [default: NULL]
  framgent_id "integer unsigned" [default: 0]
  geoip_asnum "integer unsigned" [default: 0]
  geoip_city TEXT [default: NULL]
  geoip_country TEXT [default: NULL]
  geoip_country_iso TEXT [default: NULL]
  geoip_dst_asnum "integer unsigned" [default: 0]
  geoip_dst_city TEXT [default: NULL]
  geoip_dst_country TEXT [default: NULL]
  geoip_dst_country_iso TEXT [default: NULL]
  geoip_dst_isp TEXT [default: NULL]
  geoip_dst_lat DOUBLE [default: 0]
  geoip_dst_lon DOUBLE [default: 0]
  geoip_dst_org TEXT [default: NULL]
  geoip_dst_summary TEXT [default: NULL]
  geoip_isp TEXT [default: NULL]
  geoip_lat DOUBLE [default: 0]
  geoip_lon DOUBLE [default: 0]
  geoip_org TEXT [default: NULL]
  geoip_src_asnum "integer unsigned" [default: 0]
  geoip_src_city TEXT [default: NULL]
  geoip_src_country TEXT [default: NULL]
  geoip_src_country_iso TEXT [default: NULL]
  geoip_src_isp TEXT [default: NULL]
  geoip_src_lat DOUBLE [default: 0]
  geoip_src_lon DOUBLE [default: 0]
  geoip_src_org TEXT [default: NULL]
  geoip_src_summary TEXT [default: NULL]
  hlim "tinyint unsigned" [default: 0]
  hop_opt TEXT [default: NULL]
  hopopts TEXT [default: NULL]
  hopopts_length "tinyint unsigned" [default: 0]
  hopopts_not_first TEXT [default: NULL]
  hopopts_nxt "tinyint unsigned" [default: 0]
  host TEXT [default: NULL]
  invalid_header TEXT [default: NULL]
  isatap_ipv4 VARCHAR(15) [default: NULL]
  mhome_address VARCHAR(17) [default: NULL]
  mhome_address_invalid_len TEXT [default: NULL]
  mlength "tinyint unsigned" [default: 0]
  mtype "tinyint unsigned" [default: 0]
  nxt "tinyint unsigned" [default: 0]
  opt TEXT [default: NULL]
  opt_calipso_checksum "smallint unsigned" [default: 0]
  opt_calipso_cmpt_length "tinyint unsigned" [default: 0]
  opt_calipso_cmpt_bitmap blob [default: NULL]
  opt_calipso_doi "tinyint unsigned" [default: 0]
  opt_calipso_sens_level "tinyint unsigned" [default: 0]
  opt_deprecated TEXT [default: NULL]
  opt_dff_flag_dup tinyint(1) [default: 0]
  opt_dff_flag_ret tinyint(1) [default: 0]
  opt_dff_flag_rsv "tinyint unsigned" [default: 0]
  opt_dff_flag_ver "tinyint unsigned" [default: 0]
  opt_dff_flags "tinyint unsigned" [default: 0]
  opt_dff_sequence_number "smallint unsigned" [default: 0]
  opt_experimental blob [default: NULL]
  opt_header_mismatch TEXT [default: NULL]
  opt_ilnp_nonce blob [default: NULL]
  opt_invalid_len TEXT [default: NULL]
  opt_jumbo "integer unsigned" [default: 0]
  opt_jumbo_fragment TEXT [default: NULL]
  opt_jumbo_invalid_len TEXT [default: NULL]
  opt_jumbo_missing TEXT [default: NULL]
  opt_jumbo_not_hopbyhop TEXT [default: NULL]
  opt_jumbo_prohibited TEXT [default: NULL]
  opt_jumbo_truncated TEXT [default: NULL]
  opt_length "tinyint unsigned" [default: 0]
  opt_lio_length "tinyint unsigned" [default: 0]
  opt_lio_line_id TEXT [default: NULL]
  opt_mhome_address VARCHAR(17) [default: NULL]
  opt_mpl_flag "tinyint unsigned" [default: 0]
  opt_mpl_flag_m tinyint(1) [default: 0]
  opt_mpl_flag_rsv "tinyint unsigned" [default: 0]
  opt_mpl_flag_s "tinyint unsigned" [default: 0]
  opt_mpl_flag_v tinyint(1) [default: 0]
  opt_mpl_src_seed_id TEXT [default: NULL]
  opt_mpl_seed_id blob [default: NULL]
  opt_mpl_sequence "tinyint unsigned" [default: 0]
  opt_pad1 TEXT [default: NULL]
  opt_padn blob [default: NULL]
  opt_pdm_delta_last_recv "smallint unsigned" [default: 0]
  opt_pdm_delta_last_sent "smallint unsigned" [default: 0]
  opt_pdm_psn_last_recv "smallint unsigned" [default: 0]
  opt_pdm_psn_this_pkt "smallint unsigned" [default: 0]
  opt_pdm_scale_dtlr "tinyint unsigned" [default: 0]
  opt_pdm_scale_dtls "tinyint unsigned" [default: 0]
  opt_pmtu_min "smallint unsigned" [default: 0]
  opt_pmtu_r_flag tinyint(1) [default: 0]
  opt_pmtu_rtn "smallint unsigned" [default: 0]
  opt_qs_func "tinyint unsigned" [default: 0]
  opt_qs_nonce "integer unsigned" [default: 0]
  opt_qs_rate "tinyint unsigned" [default: 0]
  opt_qs_reserved "integer unsigned" [default: 0]
  opt_qs_ttl "tinyint unsigned" [default: 0]
  opt_qs_ttl_diff "tinyint unsigned" [default: 0]
  opt_qs_unused "tinyint unsigned" [default: 0]
  opt_router_alert "smallint unsigned" [default: 0]
  opt_router_alert_invalid_len TEXT [default: NULL]
  opt_rpl_flag "tinyint unsigned" [default: 0]
  opt_rpl_flag_f tinyint(1) [default: 0]
  opt_rpl_flag_o tinyint(1) [default: 0]
  opt_rpl_flag_r tinyint(1) [default: 0]
  opt_rpl_flag_rsv "tinyint unsigned" [default: 0]
  opt_rpl_instance_id "tinyint unsigned" [default: 0]
  opt_rpl_sender_rank "smallint unsigned" [default: 0]
  opt_smf_dpd_hash_bit tinyint(1) [default: 0]
  opt_smf_dpd_hav blob [default: NULL]
  opt_smf_dpd_ident blob [default: NULL]
  opt_smf_dpd_tagger_id blob [default: NULL]
  opt_smf_dpd_tid_len "tinyint unsigned" [default: 0]
  opt_smf_dpd_tid_type "tinyint unsigned" [default: 0]
  opt_tel "tinyint unsigned" [default: 0]
  opt_tel_invalid_len TEXT [default: NULL]
  opt_tpf_information "integer unsigned" [default: 0]
  opt_type "tinyint unsigned" [default: 0]
  opt_type_action "tinyint unsigned" [default: 0]
  opt_type_change tinyint(1) [default: 0]
  opt_type_rest "tinyint unsigned" [default: 0]
  opt_unknown blob [default: NULL]
  opt_unknown_data_expert TEXT [default: NULL]
  opt_unknown_data blob [default: NULL]
  padding blob [default: NULL]
  plen "smallint unsigned" [default: 0]
  plen_exceeds_framing TEXT [default: NULL]
  plen_zero TEXT [default: NULL]
  reassembled_data blob [default: NULL]
  reassembled_in TEXT [default: NULL]
  reassembled_length "integer unsigned" [default: 0]
  reassembled_in_in TEXT [default: NULL]
  routing TEXT [default: NULL]
  routing_invalid_length TEXT [default: NULL]
  routing_invalid_segleft TEXT [default: NULL]
  routing_length "tinyint unsigned" [default: 0]
  routing_mhome_address VARCHAR(17) [default: NULL]
  routing_mreserved blob [default: NULL]
  routing_nxt "tinyint unsigned" [default: 0]
  routing_rpl_address blob [default: NULL]
  routing_rpl_cmprE "integer unsigned" [default: 0]
  routing_rpl_cmprI "integer unsigned" [default: 0]
  routing_rpl_cmprI_cmprE_pad TEXT [default: NULL]
  routing_rpl_full_address VARCHAR(17) [default: NULL]
  routing_rpl_pad "integer unsigned" [default: 0]
  routing_rpl_reserved "integer unsigned" [default: 0]
  routing_rpl_reserved_not0 TEXT [default: NULL]
  routing_rpl_segments integer [default: 0]
  routing_rpl_segments_ge0 TEXT [default: NULL]
  routing_segleft "tinyint unsigned" [default: 0]
  routing_src_addr VARCHAR(17) [default: NULL]
  routing_src_reserved blob [default: NULL]
  routing_type "tinyint unsigned" [default: 0]
  routing_hdr "tinyint unsigned" [default: 0]
  routing_hdr_addr VARCHAR(17) [default: NULL]
  routing_hdr_left "tinyint unsigned" [default: 0]
  routing_hdr_rpl_address blob [default: NULL]
  routing_hdr_rpl_cmprE "integer unsigned" [default: 0]
  routing_hdr_rpl_cmprI "integer unsigned" [default: 0]
  routing_hdr_rpl_cmprI_cmprE_pad TEXT [default: NULL]
  routing_hdr_rpl_full_address VARCHAR(17) [default: NULL]
  routing_hdr_rpl_pad "integer unsigned" [default: 0]
  routing_hdr_rpl_reserved "integer unsigned" [default: 0]
  routing_hdr_rpl_reserved_not0 TEXT [default: NULL]
  routing_hdr_rpl_segments integer [default: 0]
  routing_hdr_rpl_segments_ge0 TEXT [default: NULL]
  routing_hdr_type "tinyint unsigned" [default: 0]
  sa_mac TEXT [default: NULL]
  shim6 TEXT [default: NULL]
  shim6_cga_parameter_data_structure blob [default: NULL]
  shim6_cga_signature blob [default: NULL]
  shim6_checksum "smallint unsigned" [default: 0]
  shim6_checksum_bad tinyint(1) [default: 0]
  shim6_checksum_bad_expert TEXT [default: NULL]
  shim6_checksum_good tinyint(1) [default: 0]
  shim6_ct TEXT [default: NULL]
  shim6_inonce "integer unsigned" [default: 0]
  shim6_len "tinyint unsigned" [default: 0]
  shim6_length "tinyint unsigned" [default: 0]
  shim6_loc_flags "tinyint unsigned" [default: 0]
  shim6_loc_prio "tinyint unsigned" [default: 0]
  shim6_loc_weight "tinyint unsigned" [default: 0]
  shim6_locator VARCHAR(17) [default: NULL]
  shim6_nxt "tinyint unsigned" [default: 0]
  shim6_opt_critical tinyint(1) [default: 0]
  shim6_opt_elemlen "tinyint unsigned" [default: 0]
  shim6_opt_elemlen_invalid TEXT [default: NULL]
  shim6_opt_fii "integer unsigned" [default: 0]
  shim6_opt_len "smallint unsigned" [default: 0]
  shim6_opt_loclist "integer unsigned" [default: 0]
  shim6_opt_locnum "tinyint unsigned" [default: 0]
  shim6_opt_total_len "smallint unsigned" [default: 0]
  shim6_opt_type "smallint unsigned" [default: 0]
  shim6_opt_verif_method "tinyint unsigned" [default: 0]
  shim6_p tinyint(1) [default: 0]
  shim6_pdata "integer unsigned" [default: 0]
  shim6_pdst VARCHAR(17) [default: NULL]
  shim6_pnonce "integer unsigned" [default: 0]
  shim6_precvd "tinyint unsigned" [default: 0]
  shim6_proto "tinyint unsigned" [default: 0]
  shim6_psent "tinyint unsigned" [default: 0]
  shim6_psrc VARCHAR(17) [default: NULL]
  shim6_reap "tinyint unsigned" [default: 0]
  shim6_reserved blob [default: NULL]
  shim6_reserved2 blob [default: NULL]
  shim6_rnonce "integer unsigned" [default: 0]
  shim6_rulid VARCHAR(17) [default: NULL]
  shim6_sulid VARCHAR(17) [default: NULL]
  shim6_type "tinyint unsigned" [default: 0]
  shim6_validator blob [default: NULL]
  slaac_mac TEXT [default: NULL]
  src VARCHAR(17) [default: NULL]
  src_6to4_gw_ipv4 VARCHAR(15) [default: NULL]
  src_6to4_sla_id "smallint unsigned" [default: 0]
  src_embed_ipv4 VARCHAR(15) [default: NULL]
  src_host TEXT [default: NULL]
  src_isatap_ipv4 VARCHAR(15) [default: NULL]
  src_route_list_dst_addr TEXT [default: NULL]
  src_route_list_mult_inst_same_addr TEXT [default: NULL]
  src_route_list_multicast_addr TEXT [default: NULL]
  src_route_list_src_addr TEXT [default: NULL]
  src_sa_mac TEXT [default: NULL]
  src_slaac_mac TEXT [default: NULL]
  src_tc_ipv4 VARCHAR(15) [default: NULL]
  src_tc_port "smallint unsigned" [default: 0]
  src_ts_ipv4 VARCHAR(15) [default: NULL]
  tc_ipv4 VARCHAR(15) [default: NULL]
  tc_port "smallint unsigned" [default: 0]
  tclass "integer unsigned" [default: 0]
  tclass_dscp "integer unsigned" [default: 0]
  tclass_ecn "integer unsigned" [default: 0]
  traffic_class_ce tinyint(1) [default: 0]
  traffic_class_dscp "integer unsigned" [default: 0]
  traffic_class_ect tinyint(1) [default: 0]
  ts_ipv4 VARCHAR(15) [default: NULL]
  unknown_hdr TEXT [default: NULL]
  unknown_hdr_length "tinyint unsigned" [default: 0]
  unknown_hdr_nxt "tinyint unsigned" [default: 0]
  version "tinyint unsigned" [default: 0]
}

Table icmp {
  id integer [pk]
  addr_entry_size "tinyint unsigned" [default: 0]
  address_mask VARCHAR(15) [default: NULL]
  checksum "smallint unsigned" [default: 0]
  checksum_status "tinyint unsigned" [default: 0]
  checksum_bad TEXT [default: NULL]
  checksum_bad_expert TEXT [default: NULL]
  code "tinyint unsigned" [default: 0]
  data_time DATE [default: NULL]
  data_time_relative DOUBLE [default: 0]
  ext TEXT [default: NULL]
  ext_checksum "smallint unsigned" [default: 0]
  ext_checksum_status "tinyint unsigned" [default: 0]
  ext_checksum_bad TEXT [default: NULL]
  ext_class "tinyint unsigned" [default: 0]
  ext_ctype "tinyint unsigned" [default: 0]
  ext_data blob [default: NULL]
  ext_echo_req_local tinyint(1) [default: 0]
  ext_echo_req_res "tinyint unsigned" [default: 0]
  ext_echo_rsp_active tinyint(1) [default: 0]
  ext_echo_rsp_ipv4 tinyint(1) [default: 0]
  ext_echo_rsp_ipv6 tinyint(1) [default: 0]
  ext_echo_rsp_res "tinyint unsigned" [default: 0]
  ext_echo_rsp_state "tinyint unsigned" [default: 0]
  ext_echo_seq "tinyint unsigned" [default: 0]
  ext_length "smallint unsigned" [default: 0]
  ext_res "smallint unsigned" [default: 0]
  ext_version "tinyint unsigned" [default: 0]
  ident "smallint unsigned" [default: 0]
  ident_le "smallint unsigned" [default: 0]
  int_ident_addr_length "tinyint unsigned" [default: 0]
  int_ident_address blob [default: NULL]
  int_ident_afi "smallint unsigned" [default: 0]
  int_ident_index "integer unsigned" [default: 0]
  int_ident_ipv4 VARCHAR(15) [default: NULL]
  int_ident_ipv6 VARCHAR(17) [default: NULL]
  int_ident_name TEXT [default: NULL]
  int_ident_reserved blob [default: NULL]
  int_info_afi "smallint unsigned" [default: 0]
  int_info_ifindex tinyint(1) [default: 0]
  int_info_index "integer unsigned" [default: 0]
  int_info_ip VARCHAR(15) [default: NULL]
  int_info_ipaddr tinyint(1) [default: 0]
  int_info_ipunknown blob [default: NULL]
  int_info_ipv4 VARCHAR(15) [default: NULL]
  int_info_ipv6 VARCHAR(17) [default: NULL]
  int_info_mtu "integer unsigned" [default: 0]
  int_info_mtu_present tinyint(1) [default: 0]
  int_info_name TEXT [default: NULL]
  int_info_name_length "tinyint unsigned" [default: 0]
  int_info_name_present tinyint(1) [default: 0]
  int_info_reserved "tinyint unsigned" [default: 0]
  int_info_role "tinyint unsigned" [default: 0]
  length "tinyint unsigned" [default: 0]
  length_original_datagram "tinyint unsigned" [default: 0]
  lifetime "smallint unsigned" [default: 0]
  mip_b tinyint(1) [default: 0]
  mip_challenge blob [default: NULL]
  mip_coa VARCHAR(15) [default: NULL]
  mip_content blob [default: NULL]
  mip_f tinyint(1) [default: 0]
  mip_flags "smallint unsigned" [default: 0]
  mip_g tinyint(1) [default: 0]
  mip_h tinyint(1) [default: 0]
  mip_length "tinyint unsigned" [default: 0]
  mip_life "smallint unsigned" [default: 0]
  mip_m tinyint(1) [default: 0]
  mip_prefixlength "tinyint unsigned" [default: 0]
  mip_r tinyint(1) [default: 0]
  mip_reserved "smallint unsigned" [default: 0]
  mip_rt tinyint(1) [default: 0]
  mip_seq "smallint unsigned" [default: 0]
  mip_type "tinyint unsigned" [default: 0]
  mip_u tinyint(1) [default: 0]
  mip_v tinyint(1) [default: 0]
  mip_x tinyint(1) [default: 0]
  mpls TEXT [default: NULL]
  mpls_checksum "smallint unsigned" [default: 0]
  mpls_checksum_bad tinyint(1) [default: 0]
  mpls_class "tinyint unsigned" [default: 0]
  mpls_ctype "tinyint unsigned" [default: 0]
  mpls_data blob [default: NULL]
  mpls_exp "integer unsigned" [default: 0]
  mpls_label "integer unsigned" [default: 0]
  mpls_length "smallint unsigned" [default: 0]
  mpls_res "smallint unsigned" [default: 0]
  mpls_s tinyint(1) [default: 0]
  mpls_ttl "tinyint unsigned" [default: 0]
  mpls_version "tinyint unsigned" [default: 0]
  mtu "smallint unsigned" [default: 0]
  no_resp TEXT [default: NULL]
  num_addrs "tinyint unsigned" [default: 0]
  originate_timestamp "integer unsigned" [default: 0]
  pointer "integer unsigned" [default: 0]
  pref_level integer [default: 0]
  receive_timestamp "integer unsigned" [default: 0]
  redir_gw VARCHAR(15) [default: NULL]
  reserved blob [default: NULL]
  resp_in TEXT [default: NULL]
  resp_not_found TEXT [default: NULL]
  resp_to TEXT [default: NULL]
  resptime DOUBLE [default: 0]
  router_address VARCHAR(15) [default: NULL]
  seq "smallint unsigned" [default: 0]
  seq_le "smallint unsigned" [default: 0]
  transmit_timestamp "integer unsigned" [default: 0]
  type "tinyint unsigned" [default: 0]
  unused blob [default: NULL]

}

Table icmpv6 {
  id integer [pk]
  icmpv6_6lowpannd_da_eui64 TINYTEXT [default: NULL]
  icmpv6_6lowpannd_da_lifetime "smallint unsigned" [default: 0]
  icmpv6_6lowpannd_da_reg_addr VARCHAR(17) [default: NULL]
  icmpv6_6lowpannd_da_rsv "tinyint unsigned" [default: 0]
  icmpv6_6lowpannd_da_status "tinyint unsigned" [default: 0]
  all_comp "smallint unsigned" [default: 0]
  checksum "smallint unsigned" [default: 0]
  checksum_status "tinyint unsigned" [default: 0]
  checksum_bad tinyint(1) [default: 0]
  checksum_bad_expert TEXT [default: NULL]
  code "tinyint unsigned" [default: 0]
  comp "smallint unsigned" [default: 0]
  data blob [default: NULL]
  echo_identifier "smallint unsigned" [default: 0]
  echo_sequence_number "smallint unsigned" [default: 0]
  ext_echo_req_local tinyint(1) [default: 0]
  ext_echo_req_res "tinyint unsigned" [default: 0]
  ext_echo_rsp_active tinyint(1) [default: 0]
  ext_echo_rsp_ipv4 tinyint(1) [default: 0]
  ext_echo_rsp_ipv6 tinyint(1) [default: 0]
  ext_echo_rsp_res "tinyint unsigned" [default: 0]
  ext_echo_rsp_state "tinyint unsigned" [default: 0]
  ext_echo_seq "tinyint unsigned" [default: 0]
  fmip6_hi_flag "tinyint unsigned" [default: 0]
  fmip6_hi_flag_a tinyint(1) [default: 0]
  fmip6_hi_flag_reserved "tinyint unsigned" [default: 0]
  fmip6_hi_flag_s tinyint(1) [default: 0]
  fmip6_identifier "smallint unsigned" [default: 0]
  fmip6_subtype "tinyint unsigned" [default: 0]
  haad_ha_addrs VARCHAR(17) [default: NULL]
  identifier "smallint unsigned" [default: 0]
  ilnp_nb_lifetime "integer unsigned" [default: 0]
  ilnp_nb_locator "bigint unsigned" [default: 0]
  ilnp_nb_locs "tinyint unsigned" [default: 0]
  ilnp_nb_preference "integer unsigned" [default: 0]
  invalid_option_length TEXT [default: NULL]
  length "tinyint unsigned" [default: 0]
  mcast_ra_query_interval "smallint unsigned" [default: 0]
  mcast_ra_robustness_variable "smallint unsigned" [default: 0]
  mip6_flag "smallint unsigned" [default: 0]
  mip6_flag_m tinyint(1) [default: 0]
  mip6_flag_o tinyint(1) [default: 0]
  mip6_flag_rsv "smallint unsigned" [default: 0]
  mip6_home_agent_address VARCHAR(17) [default: NULL]
  mip6_identifier "smallint unsigned" [default: 0]
  mld_flag "tinyint unsigned" [default: 0]
  mld_flag_qrv "tinyint unsigned" [default: 0]
  mld_flag_reserved "tinyint unsigned" [default: 0]
  mld_flag_s tinyint(1) [default: 0]
  mld_maximum_response_code "smallint unsigned" [default: 0]
  mld_maximum_response_delay "smallint unsigned" [default: 0]
  mld_multicast_address VARCHAR(17) [default: NULL]
  mld_nb_sources "smallint unsigned" [default: 0]
  mld_qqi "tinyint unsigned" [default: 0]
  mld_source_address VARCHAR(17) [default: NULL]
  mldr_mar TEXT [default: NULL]
  mldr_mar_aux_data_len "tinyint unsigned" [default: 0]
  mldr_mar_auxiliary_data blob [default: NULL]
  mldr_mar_multicast_address VARCHAR(17) [default: NULL]
  mldr_mar_nb_sources "smallint unsigned" [default: 0]
  mldr_mar_record_type "tinyint unsigned" [default: 0]
  mldr_mar_source_address VARCHAR(17) [default: NULL]
  mldr_nb_mcast_records "smallint unsigned" [default: 0]
  mpl_seed_info_bm_len "tinyint unsigned" [default: 0]
  mpl_seed_info_min_sequence "tinyint unsigned" [default: 0]
  mpl_seed_info_s "tinyint unsigned" [default: 0]
  mpl_seed_info_seed_id TEXT [default: NULL]
  mpl_seed_info_sequence "tinyint unsigned" [default: 0]
  mtu "integer unsigned" [default: 0]
  nd_na_flag "integer unsigned" [default: 0]
  nd_na_flag_o tinyint(1) [default: 0]
  nd_na_flag_r tinyint(1) [default: 0]
  nd_na_flag_rsv "integer unsigned" [default: 0]
  nd_na_flag_s tinyint(1) [default: 0]
  nd_na_target_address VARCHAR(17) [default: NULL]
  nd_ns_target_address VARCHAR(17) [default: NULL]
  nd_ra_cur_hop_limit "tinyint unsigned" [default: 0]
  nd_ra_flag "tinyint unsigned" [default: 0]
  nd_ra_flag_h tinyint(1) [default: 0]
  nd_ra_flag_m tinyint(1) [default: 0]
  nd_ra_flag_o tinyint(1) [default: 0]
  nd_ra_flag_p tinyint(1) [default: 0]
  nd_ra_flag_prf "tinyint unsigned" [default: 0]
  nd_ra_flag_rsv "tinyint unsigned" [default: 0]
  nd_ra_reachable_time "integer unsigned" [default: 0]
  nd_ra_retrans_timer "integer unsigned" [default: 0]
  nd_ra_router_lifetime "smallint unsigned" [default: 0]
  nd_rd_target_address VARCHAR(17) [default: NULL]
  ni_flag "smallint unsigned" [default: 0]
  ni_flag_a tinyint(1) [default: 0]
  ni_flag_c tinyint(1) [default: 0]
  ni_flag_g tinyint(1) [default: 0]
  ni_flag_l tinyint(1) [default: 0]
  ni_flag_rsv "smallint unsigned" [default: 0]
  ni_flag_s tinyint(1) [default: 0]
  ni_flag_t tinyint(1) [default: 0]
  ni_nonce "bigint unsigned" [default: 0]
  ni_qtype "smallint unsigned" [default: 0]
  ni_query_ipv4_address VARCHAR(15) [default: NULL]
  ni_query_node_address VARCHAR(17) [default: NULL]
  ni_query_node_name TEXT [default: NULL]
  ni_query_subject_fqdn TEXT [default: NULL]
  ni_query_subject_ipv4 VARCHAR(15) [default: NULL]
  ni_query_subject_ipv6 VARCHAR(17) [default: NULL]
  ni_reply_ipv4_address VARCHAR(15) [default: NULL]
  ni_reply_node_address VARCHAR(17) [default: NULL]
  ni_reply_node_name TEXT [default: NULL]
  ni_reply_node_ttl "integer unsigned" [default: 0]
  no_resp TEXT [default: NULL]
  nonce blob [default: NULL]
  nor "smallint unsigned" [default: 0]
  opt TEXT [default: NULL]
  opt_6cio_flag_g "smallint unsigned" [default: 0]
  opt_6cio_unassigned1 "smallint unsigned" [default: 0]
  opt_6cio_unassigned2 "integer unsigned" [default: 0]
  opt_6co_context_length "tinyint unsigned" [default: 0]
  opt_6co_context_prefix VARCHAR(17) [default: NULL]
  opt_6co_flag "tinyint unsigned" [default: 0]
  opt_6co_flag_c tinyint(1) [default: 0]
  opt_6co_flag_cid "tinyint unsigned" [default: 0]
  opt_6co_flag_reserved "tinyint unsigned" [default: 0]
  opt_6co_valid_lifetime "smallint unsigned" [default: 0]
  opt_abro_6lbr_address VARCHAR(17) [default: NULL]
  opt_abro_valid_lifetime "smallint unsigned" [default: 0]
  opt_abro_version "smallint unsigned" [default: 0]
  opt_abro_version_high "smallint unsigned" [default: 0]
  opt_abro_version_low "smallint unsigned" [default: 0]
  opt_advertisement_interval "integer unsigned" [default: 0]
  opt_aro_eui64 TINYTEXT [default: NULL]
  opt_aro_registration_lifetime "smallint unsigned" [default: 0]
  opt_aro_status "tinyint unsigned" [default: 0]
  opt_captive_portal TEXT [default: NULL]
  opt_certificate_padding TEXT [default: NULL]
  opt_cga blob [default: NULL]
  opt_cga_count blob [default: NULL]
  opt_cga_ext_data blob [default: NULL]
  opt_cga_ext_length "smallint unsigned" [default: 0]
  opt_cga_ext_type "smallint unsigned" [default: 0]
  opt_cga_modifier blob [default: NULL]
  opt_cga_pad_length "tinyint unsigned" [default: 0]
  opt_cga_subnet_prefix blob [default: NULL]
  opt_digital_signature_padding TEXT [default: NULL]
  opt_dnssl TEXT [default: NULL]
  opt_dnssl_lifetime "integer unsigned" [default: 0]
  opt_efo "smallint unsigned" [default: 0]
  opt_efo_h tinyint(1) [default: 0]
  opt_efo_m tinyint(1) [default: 0]
  opt_efo_o tinyint(1) [default: 0]
  opt_efo_p tinyint(1) [default: 0]
  opt_efo_prf "smallint unsigned" [default: 0]
  opt_efo_rsv "smallint unsigned" [default: 0]
  opt_hai_length "tinyint unsigned" [default: 0]
  opt_hai_option_code "tinyint unsigned" [default: 0]
  opt_hai_value blob [default: NULL]
  opt_hkr_at "tinyint unsigned" [default: 0]
  opt_hkr_encrypted_handover_key blob [default: NULL]
  opt_hkr_encryption_public_key blob [default: NULL]
  opt_hkr_lifetime "smallint unsigned" [default: 0]
  opt_hkr_pad_length "tinyint unsigned" [default: 0]
  opt_hkr_padding blob [default: NULL]
  opt_hkr_reserved "tinyint unsigned" [default: 0]
  opt_home_agent_lifetime "smallint unsigned" [default: 0]
  opt_home_agent_preference "smallint unsigned" [default: 0]
  opt_ipa_ipv6_address VARCHAR(17) [default: NULL]
  opt_ipa_option_code "tinyint unsigned" [default: 0]
  opt_ipa_prefix_len "tinyint unsigned" [default: 0]
  opt_ipv6_address VARCHAR(17) [default: NULL]
  opt_length "tinyint unsigned" [default: 0]
  opt_linkaddr blob [default: NULL]
  opt_linkaddr_eui64 TINYTEXT [default: NULL]
  opt_lla_bytes blob [default: NULL]
  opt_lla_option_code "tinyint unsigned" [default: 0]
  opt_map_distance "tinyint unsigned" [default: 0]
  opt_map_flag "tinyint unsigned" [default: 0]
  opt_map_flag_r tinyint(1) [default: 0]
  opt_map_flag_reserved "tinyint unsigned" [default: 0]
  opt_map_global_address VARCHAR(17) [default: NULL]
  opt_map_preference "tinyint unsigned" [default: 0]
  opt_map_valid_lifetime "integer unsigned" [default: 0]
  opt_mn_length "tinyint unsigned" [default: 0]
  opt_mn_option_code "tinyint unsigned" [default: 0]
  opt_mn_value blob [default: NULL]
  opt_mtu "integer unsigned" [default: 0]
  opt_naack_option_code "tinyint unsigned" [default: 0]
  opt_naack_status "tinyint unsigned" [default: 0]
  opt_naack_supplied_ncoa VARCHAR(17) [default: NULL]
  opt_name_type "tinyint unsigned" [default: 0]
  opt_name_type_fqdn TEXT [default: NULL]
  opt_name_x501 blob [default: NULL]
  opt_nbma_shortcut_limit "tinyint unsigned" [default: 0]
  opt_nonce blob [default: NULL]
  opt_nrpi_option_code "tinyint unsigned" [default: 0]
  opt_nrpi_prefix VARCHAR(17) [default: NULL]
  opt_nrpi_prefix_len "tinyint unsigned" [default: 0]
  opt_padding TEXT [default: NULL]
  opt_pref64_plc "smallint unsigned" [default: 0]
  opt_pref64_prefix VARCHAR(17) [default: NULL]
  opt_pref64_scaled_lifetime "smallint unsigned" [default: 0]
  opt_prefix VARCHAR(17) [default: NULL]
  opt_prefix_flag "tinyint unsigned" [default: 0]
  opt_prefix_flag_a tinyint(1) [default: 0]
  opt_prefix_flag_l tinyint(1) [default: 0]
  opt_prefix_flag_r tinyint(1) [default: 0]
  opt_prefix_flag_reserved "tinyint unsigned" [default: 0]
  opt_prefix_length "tinyint unsigned" [default: 0]
  opt_prefix_preferred_lifetime "integer unsigned" [default: 0]
  opt_prefix_valid_lifetime "integer unsigned" [default: 0]
  opt_ps_key_hash blob [default: NULL]
  opt_rdnss VARCHAR(17) [default: NULL]
  opt_rdnss_lifetime "integer unsigned" [default: 0]
  opt_redirected_packet TEXT [default: NULL]
  opt_reserved TEXT [default: NULL]
  opt_route_info_flag "tinyint unsigned" [default: 0]
  opt_route_info_flag_reserved "tinyint unsigned" [default: 0]
  opt_route_info_flag_route_preference "tinyint unsigned" [default: 0]
  opt_route_lifetime "integer unsigned" [default: 0]
  opt_rsa_key_hash blob [default: NULL]
  opt_src_linkaddr blob [default: NULL]
  opt_src_linkaddr_eui64 TINYTEXT [default: NULL]
  opt_target_linkaddr blob [default: NULL]
  opt_target_linkaddr_eui64 TINYTEXT [default: NULL]
  opt_timestamp DATE [default: NULL]
  opt_type "tinyint unsigned" [default: 0]
  opt_prefix_flag_a_a tinyint(1) [default: 0]
  opt_prefix_flag_l_l tinyint(1) [default: 0]
  opt_prefix_flag_reserved_r "tinyint unsigned" [default: 0]
  opt_prefix_length_l "tinyint unsigned" [default: 0]
  option TEXT [default: NULL]
  option_cga blob [default: NULL]
  option_cga_count blob [default: NULL]
  option_cga_ext_length blob [default: NULL]
  option_cga_ext_type blob [default: NULL]
  option_cga_modifier blob [default: NULL]
  option_cga_pad_length "tinyint unsigned" [default: 0]
  option_cga_subnet_prefix blob [default: NULL]
  option_length "tinyint unsigned" [default: 0]
  option_name_type "tinyint unsigned" [default: 0]
  option_name_type_fqdn TEXT [default: NULL]
  option_name_x501 blob [default: NULL]
  option_rsa_key_hash blob [default: NULL]
  option_type "tinyint unsigned" [default: 0]
  pointer "integer unsigned" [default: 0]
  ra_cur_hop_limit "tinyint unsigned" [default: 0]
  ra_reachable_time "integer unsigned" [default: 0]
  ra_retrans_timer "integer unsigned" [default: 0]
  ra_router_lifetime "smallint unsigned" [default: 0]
  rd_na_destination_address VARCHAR(17) [default: NULL]
  recursive_dns_serv VARCHAR(17) [default: NULL]
  reserved blob [default: NULL]
  resp_in TEXT [default: NULL]
  resp_not_found TEXT [default: NULL]
  resp_to TEXT [default: NULL]
  resptime DOUBLE [default: 0]
  rpl_cc_destination_counter "integer unsigned" [default: 0]
  rpl_cc_dodagid VARCHAR(17) [default: NULL]
  rpl_cc_flag "tinyint unsigned" [default: 0]
  rpl_cc_flag_r tinyint(1) [default: 0]
  rpl_cc_flag_rsv "tinyint unsigned" [default: 0]
  rpl_cc_instance "tinyint unsigned" [default: 0]
  rpl_cc_nonce "smallint unsigned" [default: 0]
  rpl_dao_dodagid VARCHAR(17) [default: NULL]
  rpl_dao_flag "tinyint unsigned" [default: 0]
  rpl_dao_flag_d tinyint(1) [default: 0]
  rpl_dao_flag_k tinyint(1) [default: 0]
  rpl_dao_flag_rsv "tinyint unsigned" [default: 0]
  rpl_dao_instance "tinyint unsigned" [default: 0]
  rpl_dao_sequence "tinyint unsigned" [default: 0]
  rpl_daoack_dodagid VARCHAR(17) [default: NULL]
  rpl_daoack_flag "tinyint unsigned" [default: 0]
  rpl_daoack_flag_d tinyint(1) [default: 0]
  rpl_daoack_flag_rsv "tinyint unsigned" [default: 0]
  rpl_daoack_instance "tinyint unsigned" [default: 0]
  rpl_daoack_sequence "tinyint unsigned" [default: 0]
  rpl_daoack_status "tinyint unsigned" [default: 0]
  rpl_dio_dagid VARCHAR(17) [default: NULL]
  rpl_dio_dtsn "tinyint unsigned" [default: 0]
  rpl_dio_flag "tinyint unsigned" [default: 0]
  rpl_dio_flag_0 tinyint(1) [default: 0]
  rpl_dio_flag_g tinyint(1) [default: 0]
  rpl_dio_flag_mop "tinyint unsigned" [default: 0]
  rpl_dio_flag_preference "tinyint unsigned" [default: 0]
  rpl_dio_instance "tinyint unsigned" [default: 0]
  rpl_dio_rank "smallint unsigned" [default: 0]
  rpl_dio_version "tinyint unsigned" [default: 0]
  rpl_dis_flags "tinyint unsigned" [default: 0]
  rpl_opt_config_auth tinyint(1) [default: 0]
  rpl_opt_config_def_lifetime "tinyint unsigned" [default: 0]
  rpl_opt_config_flag "tinyint unsigned" [default: 0]
  rpl_opt_config_flag_a tinyint(1) [default: 0]
  rpl_opt_config_flag_r tinyint(1) [default: 0]
  rpl_opt_config_flag_rsv "tinyint unsigned" [default: 0]
  rpl_opt_config_interval_double "tinyint unsigned" [default: 0]
  rpl_opt_config_interval_min "smallint unsigned" [default: 0]
  rpl_opt_config_lifetime_unit "smallint unsigned" [default: 0]
  rpl_opt_config_max_rank_inc "smallint unsigned" [default: 0]
  rpl_opt_config_min_hop_rank_inc "smallint unsigned" [default: 0]
  rpl_opt_config_ocp "smallint unsigned" [default: 0]
  rpl_opt_config_pcs "tinyint unsigned" [default: 0]
  rpl_opt_config_redundancy "tinyint unsigned" [default: 0]
  rpl_opt_config_reserved "tinyint unsigned" [default: 0]
  rpl_opt_config_rsv "tinyint unsigned" [default: 0]
  rpl_opt_length "tinyint unsigned" [default: 0]
  rpl_opt_metric_etx_object_etx "smallint unsigned" [default: 0]
  rpl_opt_metric_flag_a "smallint unsigned" [default: 0]
  rpl_opt_metric_flag_c tinyint(1) [default: 0]
  rpl_opt_metric_flag_o tinyint(1) [default: 0]
  rpl_opt_metric_flag_p tinyint(1) [default: 0]
  rpl_opt_metric_flag_r tinyint(1) [default: 0]
  rpl_opt_metric_flags "smallint unsigned" [default: 0]
  rpl_opt_metric_hp_object "smallint unsigned" [default: 0]
  rpl_opt_metric_hp_object_flags "smallint unsigned" [default: 0]
  rpl_opt_metric_hp_object_hp "smallint unsigned" [default: 0]
  rpl_opt_metric_hp_object_reserved "smallint unsigned" [default: 0]
  rpl_opt_metric_lc_object TEXT [default: NULL]
  rpl_opt_metric_lc_object_counter "smallint unsigned" [default: 0]
  rpl_opt_metric_lc_object_flag_i "smallint unsigned" [default: 0]
  rpl_opt_metric_lc_object_lc "smallint unsigned" [default: 0]
  rpl_opt_metric_lc_object_res "tinyint unsigned" [default: 0]
  rpl_opt_metric_lc_object_reserved "smallint unsigned" [default: 0]
  rpl_opt_metric_length "tinyint unsigned" [default: 0]
  rpl_opt_metric_ll_object_ll "integer unsigned" [default: 0]
  rpl_opt_metric_lql_object "tinyint unsigned" [default: 0]
  rpl_opt_metric_lql_object_counter "tinyint unsigned" [default: 0]
  rpl_opt_metric_lql_object_res "tinyint unsigned" [default: 0]
  rpl_opt_metric_lql_object_val "tinyint unsigned" [default: 0]
  rpl_opt_metric_lt_object_lt "integer unsigned" [default: 0]
  rpl_opt_metric_ne_object "smallint unsigned" [default: 0]
  rpl_opt_metric_ne_object_energy "smallint unsigned" [default: 0]
  rpl_opt_metric_ne_object_flag_e tinyint(1) [default: 0]
  rpl_opt_metric_ne_object_flag_i tinyint(1) [default: 0]
  rpl_opt_metric_ne_object_flags "smallint unsigned" [default: 0]
  rpl_opt_metric_ne_object_type "smallint unsigned" [default: 0]
  rpl_opt_metric_nsa_object "smallint unsigned" [default: 0]
  rpl_opt_metric_nsa_object_flag_a tinyint(1) [default: 0]
  rpl_opt_metric_nsa_object_flag_o tinyint(1) [default: 0]
  rpl_opt_metric_nsa_object_flags "smallint unsigned" [default: 0]
  rpl_opt_metric_nsa_object_opttlv_object "tinyint unsigned" [default: 0]
  rpl_opt_metric_nsa_object_opttlv_object_data blob [default: NULL]
  rpl_opt_metric_nsa_object_opttlv_object_length "tinyint unsigned" [default: 0]
  rpl_opt_metric_nsa_object_opttlv_object_type "tinyint unsigned" [default: 0]
  rpl_opt_metric_nsa_object_reserved "smallint unsigned" [default: 0]
  rpl_opt_metric_prec "smallint unsigned" [default: 0]
  rpl_opt_metric_reserved "smallint unsigned" [default: 0]
  rpl_opt_metric_type "tinyint unsigned" [default: 0]
  rpl_opt_padn TEXT [default: NULL]
  rpl_opt_prefix VARCHAR(17) [default: NULL]
  rpl_opt_prefix_flag "tinyint unsigned" [default: 0]
  rpl_opt_prefix_flag_l tinyint(1) [default: 0]
  rpl_opt_prefix_length "tinyint unsigned" [default: 0]
  rpl_opt_prefix_preferred_lifetime "integer unsigned" [default: 0]
  rpl_opt_prefix_valid_lifetime "integer unsigned" [default: 0]
  rpl_opt_reserved TEXT [default: NULL]
  rpl_opt_route_flag "tinyint unsigned" [default: 0]
  rpl_opt_route_lifetime "integer unsigned" [default: 0]
  rpl_opt_route_pref "tinyint unsigned" [default: 0]
  rpl_opt_route_prefix VARCHAR(17) [default: NULL]
  rpl_opt_route_prefix_length "tinyint unsigned" [default: 0]
  rpl_opt_route_reserved "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_addr_vec TEXT [default: NULL]
  rpl_opt_routediscovery_addrvec_addr VARCHAR(17) [default: NULL]
  rpl_opt_routediscovery_flag TEXT [default: NULL]
  rpl_opt_routediscovery_flag_compr "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_flag_hopbyhop tinyint(1) [default: 0]
  rpl_opt_routediscovery_flag_numofroutes "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_flag_reply tinyint(1) [default: 0]
  rpl_opt_routediscovery_lifetime "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_maxrank "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_nh "tinyint unsigned" [default: 0]
  rpl_opt_routediscovery_targetaddr VARCHAR(17) [default: NULL]
  rpl_opt_solicited_dodagid VARCHAR(17) [default: NULL]
  rpl_opt_solicited_flag "tinyint unsigned" [default: 0]
  rpl_opt_solicited_flag_d tinyint(1) [default: 0]
  rpl_opt_solicited_flag_i tinyint(1) [default: 0]
  rpl_opt_solicited_flag_rsv "tinyint unsigned" [default: 0]
  rpl_opt_solicited_flag_v tinyint(1) [default: 0]
  rpl_opt_solicited_instance "tinyint unsigned" [default: 0]
  rpl_opt_solicited_version "tinyint unsigned" [default: 0]
  rpl_opt_target_flag TEXT [default: NULL]
  rpl_opt_target_prefix VARCHAR(17) [default: NULL]
  rpl_opt_target_prefix_length "tinyint unsigned" [default: 0]
  rpl_opt_targetdesc_descriptor "integer unsigned" [default: 0]
  rpl_opt_transit_flag "tinyint unsigned" [default: 0]
  rpl_opt_transit_flag_e tinyint(1) [default: 0]
  rpl_opt_transit_flag_rsv "tinyint unsigned" [default: 0]
  rpl_opt_transit_parent VARCHAR(17) [default: NULL]
  rpl_opt_transit_pathctl "tinyint unsigned" [default: 0]
  rpl_opt_transit_pathlifetime "tinyint unsigned" [default: 0]
  rpl_opt_transit_pathseq "tinyint unsigned" [default: 0]
  rpl_opt_type "tinyint unsigned" [default: 0]
  rpl_p2p_dro_dagid VARCHAR(17) [default: NULL]
  rpl_p2p_dro_flag "smallint unsigned" [default: 0]
  rpl_p2p_dro_flag_ack tinyint(1) [default: 0]
  rpl_p2p_dro_flag_reserved "smallint unsigned" [default: 0]
  rpl_p2p_dro_flag_seq "smallint unsigned" [default: 0]
  rpl_p2p_dro_flag_stop tinyint(1) [default: 0]
  rpl_p2p_dro_instance "tinyint unsigned" [default: 0]
  rpl_p2p_dro_rdo_zero TEXT [default: NULL]
  rpl_p2p_dro_version "tinyint unsigned" [default: 0]
  rpl_p2p_dro_zero TEXT [default: NULL]
  rpl_p2p_droack_flag "smallint unsigned" [default: 0]
  rpl_p2p_droack_flag_reserved "smallint unsigned" [default: 0]
  rpl_p2p_droack_flag_seq "smallint unsigned" [default: 0]
  rpl_p2p_hop_by_hop TEXT [default: NULL]
  rpl_p2p_num_of_routes TEXT [default: NULL]
  rpl_secure_algorithm "tinyint unsigned" [default: 0]
  rpl_secure_algorithm_encryption "tinyint unsigned" [default: 0]
  rpl_secure_algorithm_signature "tinyint unsigned" [default: 0]
  rpl_secure_counter "integer unsigned" [default: 0]
  rpl_secure_flag "tinyint unsigned" [default: 0]
  rpl_secure_flag_rsv "tinyint unsigned" [default: 0]
  rpl_secure_flag_t tinyint(1) [default: 0]
  rpl_secure_key_index "tinyint unsigned" [default: 0]
  rpl_secure_key_source blob [default: NULL]
  rpl_secure_kim "tinyint unsigned" [default: 0]
  rpl_secure_lvl "tinyint unsigned" [default: 0]
  rpl_secure_rsv "tinyint unsigned" [default: 0]
  rpl_unknown_metric TEXT [default: NULL]
  rr_flag "tinyint unsigned" [default: 0]
  rr_flag_a tinyint(1) [default: 0]
  rr_flag_p tinyint(1) [default: 0]
  rr_flag_r tinyint(1) [default: 0]
  rr_flag_rsv "tinyint unsigned" [default: 0]
  rr_flag_s tinyint(1) [default: 0]
  rr_flag_t tinyint(1) [default: 0]
  rr_maxdelay "smallint unsigned" [default: 0]
  rr_pco_mp TEXT [default: NULL]
  rr_pco_mp_matchedlen_gt128 TEXT [default: NULL]
  rr_pco_mp_matchlen "tinyint unsigned" [default: 0]
  rr_pco_mp_matchlen_gt128 TEXT [default: NULL]
  rr_pco_mp_matchprefix VARCHAR(17) [default: NULL]
  rr_pco_mp_maxlen "tinyint unsigned" [default: 0]
  rr_pco_mp_minlen "tinyint unsigned" [default: 0]
  rr_pco_mp_opcode "tinyint unsigned" [default: 0]
  rr_pco_mp_oplength "tinyint unsigned" [default: 0]
  rr_pco_mp_ordinal "tinyint unsigned" [default: 0]
  rr_pco_up TEXT [default: NULL]
  rr_pco_up_flag "integer unsigned" [default: 0]
  rr_pco_up_flag_p tinyint(1) [default: 0]
  rr_pco_up_flag_reserved "integer unsigned" [default: 0]
  rr_pco_up_flag_v tinyint(1) [default: 0]
  rr_pco_up_flagmask "tinyint unsigned" [default: 0]
  rr_pco_up_flagmask_a tinyint(1) [default: 0]
  rr_pco_up_flagmask_l tinyint(1) [default: 0]
  rr_pco_up_flagmask_reserved "tinyint unsigned" [default: 0]
  rr_pco_up_keeplen "tinyint unsigned" [default: 0]
  rr_pco_up_preferredlifetime "integer unsigned" [default: 0]
  rr_pco_up_raflags "tinyint unsigned" [default: 0]
  rr_pco_up_uselen "tinyint unsigned" [default: 0]
  rr_pco_up_useprefix VARCHAR(17) [default: NULL]
  rr_pco_up_validlifetime "integer unsigned" [default: 0]
  rr_rm TEXT [default: NULL]
  rr_rm_flag "smallint unsigned" [default: 0]
  rr_rm_flag_b tinyint(1) [default: 0]
  rr_rm_flag_f tinyint(1) [default: 0]
  rr_rm_flag_reserved "smallint unsigned" [default: 0]
  rr_rm_interfaceindex "integer unsigned" [default: 0]
  rr_rm_matchedlen "tinyint unsigned" [default: 0]
  rr_rm_matchedprefix VARCHAR(17) [default: NULL]
  rr_rm_ordinal "tinyint unsigned" [default: 0]
  rr_segment_number "tinyint unsigned" [default: 0]
  rr_sequence_number "integer unsigned" [default: 0]
  send_all_components "smallint unsigned" [default: 0]
  send_component "smallint unsigned" [default: 0]
  send_identifier "smallint unsigned" [default: 0]
  type "tinyint unsigned" [default: 0]
  undecoded_option TEXT [default: NULL]
  undecoded_rpl_option TEXT [default: NULL]
  undecoded_type TEXT [default: NULL]
  unknown_data blob [default: NULL]
  unknown_data_expert TEXT [default: NULL]
  x509_Certificate TEXT [default: NULL]
  x509_Name "integer unsigned" [default: 0]
  x509_Certificate_C TEXT [default: NULL]
}

Table igmp {id integer [pk]
} // Placeholder

Table bgp {id integer [pk]
} // Placeholder

Table ospf {id integer [pk]
} // Placeholder

Table rip {id integer [pk]
} // Placeholder

Table ripng {id integer [pk]
} // Placeholder

Table dsr {id integer [pk]
} // Placeholder

Table ah {id integer [pk]
} // Placeholder

Table esp {id integer [pk]
} // Placeholder

Table dccp {id integer [pk]
} // Placeholder

Table sctp {id integer [pk]
} // Placeholder

Table udp {
  id integer [pk, ref: - capture.id]
  checksum "smallint unsigned" [default: 0]
  checksum_bad text [default: NULL]
  checksum_status "tinyint unsigned" [default: 0]
  checksum_zero text [default: NULL]
  checksum_bad_bool tinyint(1) [default: 0]
  checksum_bad_expert text [default: NULL]
  checksum_calculated "smallint unsigned" [default: 0]
  checksum_coverage_expert text [default: NULL]
  checksum_good tinyint(1) [default: 0]
  dstport "smallint unsigned" [default: 0]
  length "smallint unsigned" [default: 0]
  length_bad text [default: NULL]
  length_bad_zero text [default: NULL]
  payload longblob [default: NULL]
  pdu_size "integer unsigned" [default: 0]
  port "smallint unsigned" [default: 0]
  possible_traceroute text [default: NULL]
  proc_dstcmd text [default: NULL]
  proc_dstpid "integer unsigned" [default: 0]
  proc_dstuid "integer unsigned" [default: 0]
  proc_dstuname text [default: NULL]
  proc_srccmd text [default: NULL]
  proc_srcpid "integer unsigned" [default: 0]
  proc_srcuid "integer unsigned" [default: 0]
  proc_srcuname text [default: NULL]
  srcport "smallint unsigned" [default: 0]
  stream "integer unsigned" [default: 0]
  time_delta double [default: 0]
  time_relative double [default: 0]
  udplite_checksum_coverage_bad text [default: NULL]
}

Table udplite {id integer [pk]
} // Placeholder

Table tcp {id integer [pk]
} // Placeholder

Table portreference {id integer [pk]
} // Placeholder

Table rtp {id integer [pk]
} // Placeholder

Table rtcp {id integer [pk]
} // Placeholder

Table netbios {id integer [pk]
} // Placeholder

Table netdump {id integer [pk]
} // Placeholder

Table oncrpc {id integer [pk]
} // Placeholder

Table dcerpc {id integer [pk]
} // Placeholder

Table http {id integer [pk]
} // Placeholder

Table smtp {id integer [pk]
} // Placeholder

Table ancp {id integer [pk]
} // Placeholder

Table bootp {id integer [pk]
} // Placeholder

Table dhcp {id integer [pk]
} // Placeholder

Table dns {id integer [pk]
} // Placeholder

Table ftp {id integer [pk]
} // Placeholder

Table imap {id integer [pk]
} // Placeholder

Table iwarpddp {id integer [pk]
} // Placeholder

Table iwarpmpa {id integer [pk]
} // Placeholder

Table iwarprdmap {id integer [pk]
} // Placeholder

Table nntp {id integer [pk]
} // Placeholder

Table ntp {id integer [pk]
} // Placeholder

Table pana {id integer [pk]
} // Placeholder

Table pop {id integer [pk]
} // Placeholder

Table radius {id integer [pk]
} // Placeholder

Table rlogin {id integer [pk]
} // Placeholder

Table rsip {id integer [pk]
} // Placeholder

Table ssh {id integer [pk]
} // Placeholder

Table snmp {id integer [pk]
} // Placeholder

Table telnet {id integer [pk]
} // Placeholder

Table tftp {id integer [pk]
} // Placeholder

Table sasp {id integer [pk]
} // Placeholder



Tablegroup layers {
  frame
  eth
  
  // Link Layer
  arp
  rarp
  
  // Link Layer Serial line
  ppp
  //ipv // IP in every packet
  
  // Network Layer
  ip
  ipv6
  icmp
  icmpv6
  igmp
  
  
  // Network layer routing
  bgp
  ospf
  rip
  ripng
  dsr
  
  // Network layer (ipsec)
  ah
  esp
  
  // Transport layer
  dccp
  sctp
  udp
  udplite
  tcp
  portreference
  
  // UDP Transport layer
  rtp
  rtcp
  
  // Session Layer
  netbios
  netdump
  oncrpc
  dcerpc
  http
  smtp
  
  // Application Layer
  ancp
  bootp
  dhcp
  dns
  ftp
  imap
  iwarpddp
  iwarpmpa
  iwarprdmap
  nntp
  ntp
  pana
  pop
  radius
  rlogin
  rsip
  ssh
  snmp
  telnet
  tftp
  sasp
}

